### ISSUE TITLE
Default trust store not found

### ISSUE THREAD

**Issue by BamDoo** [awslabs/aws-c-io#561]
I'm trying to use AWS CRT client, however initialization is failing with 

```
Caused by: s.amazon.awssdk.crt.CrtRuntimeException: TlsContext.tls_ctx_new: Failed to create new aws_tls_ctx (aws_last_error: AWS_IO_TLS_ERROR_DEFAULT_TRUST_STORE_NOT_FOUND(1173), Default TLS trust store not found on this system. Trusted CA certificates must be installed, or "override default trust store" must be used while creating the TLS context.)
	at software.amazon.awssdk.crt.io.TlsContext.tlsContextNew(TlsContext.java)
	at software.amazon.awssdk.crt.io.TlsContext.<init>(TlsContext.java:24)
	at s.a.a.http.crt.AwsCrtAsyncHttpClient.<init>(AwsCrtAsyncHttpClient.java:104)
	at s.a.a.http.crt.AwsCrtAsyncHttpClient.<init>(AwsCrtAsyncHttpClient.java:73)
	at s.a.a.h.c.AwsCrtAsyncHttpClient$DefaultBuilder.buildWithDefaults(AwsCrtAsyncHttpClient.java:405)
```

Default cacert is available at JAVA_HOME/jre/lib/security/cacerts..... is there something else we need to configure. 

This is the sample code

```
return AwsCrtAsyncHttpClient.builder().build()
```

Related discussion: https://github.com/aws/aws-sdk-java-v2/discussions/3898

**Comment by graebm** [comment]
https://github.com/aws/aws-sdk-java-v2/discussions/3898#discussioncomment-5612167

Looks like installing the ca-certificates package fixed it for you
